services:
  - type: web
    name: yelpcamp-backend
    env: node
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 